### ISSUE TITLE
Request.

### ISSUE THREAD

**Issue by Revel8804** [HughesMDflyer4/MSFSLayoutGenerator#2]
I do not know another way to message you.

I am working on creating a blender template for all the aircraft and would like to create a script that, once you are done editing you can run the script and everything will magically be done for you.

I would like to include either your code or application into this.

Figured I would reach out and ask permission., instead of just doing it.

[Here is one of the templates I am working on.](https://git.revelcomtech.com/kenny/747-template)
Also will take any thoughts or feedback that you may have.

**Comment by HughesMDflyer4** [comment]
These templates are a great idea! Feel free to use the application or code, whichever you prefer.

I'm also on Reddit, Twitter, and Discord (#2596) with the same username if you need to contact me further.
