### ISSUE TITLE
[req] Update manifest.json package size

### ISSUE THREAD

**Issue by mixMugz** [HughesMDflyer4/MSFSLayoutGenerator#3]
Hi!

Thank you a lot for this perfect tool!!!
Can you add small feature to add:

1. After updating layout.json collect full current folder(with subfolders) size in bytes (for all files even layout.json/manifest.json and all other)
2. If manifest.json exist - update  "total_package_size" with folder size

Thanks a lot

**Comment by mixMugz** [comment]
Thanks man! It's really amazing!

**Comment by HughesMDflyer4** [comment]
Thanks for the suggestion! Glad the app has been useful.
