### ISSUE TITLE
Issue: manifest.json

### ISSUE THREAD

**Issue by mixMugz** [HughesMDflyer4/MSFSLayoutGenerator#7]
If MSFSLayoutGenerator update manifest.json file (calculate size), thee he change some unicode (special) characters to unicode code.

Example symbols:  `&+'<>

![image](https://user-images.githubusercontent.com/17923916/131260575-1663b876-0431-43c5-966c-c01c85103b4d.png)

**Comment by HughesMDflyer4** [comment]
Fixed in v1.1.1. Sorry for taking so long to get to this! Thanks for submitting the issue. :)
